#! /bin/sh


app_name="Grbr.app"
if [ $1 == "mac" ]; then
  echo 'remove the existing application'
  rm -rf $app_name
  echo 'copy Electron.app to current directory'
  cp -a node_modules/electron/dist/Electron.app $app_name
  echo 'create app.asar'
  npm run asar
  echo 'activate app.asar as an application'
  mv ./app.asar $app_name/Contents/Resources
  echo 'done'
fi
